# USA Real Estate Data- Cleaning

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
USA_ESTATE = pd.read_csv('sample.csv')
USA_ESTATE = USA_ESTATE.copy()

In [3]:
USA_ESTATE.shape

(100000, 12)

In [4]:
USA_ESTATE.head()

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,prev_sold_date
0,54239.0,sold,275000.0,1.0,1.0,NaN,1617038.0,Miami,Florida,33156.0,846.0,2022-02-28
1,90564.0,sold,399900.0,1.0,1.0,NaN,1497499.0,San Diego,California,92108.0,667.0,2022-04-28
2,53271.0,for_sale,75000.0,NaN,NaN,2.25,1877529.0,Oceola Township,Michigan,48855.0,NaN,NaN
3,12926.0,sold,325000.0,3.0,2.0,0.09,892999.0,Worcester,Massachusetts,1603.0,1409.0,2021-11-29
4,79221.0,for_sale,169900.0,NaN,NaN,3.70,1998116.0,Holmen,Wisconsin,54636.0,NaN,NaN

In [5]:
USA_ESTATE.tail()

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,prev_sold_date
99995,78553.0,for_sale,249900.0,NaN,NaN,13.51,1876588.0,Sylva,North Carolina,28779.0,NaN,NaN
99996,23001.0,sold,58000.0,2.0,1.0,0.16,663594.0,Streator,Illinois,61364.0,1050.0,2021-11-24
99997,81218.0,sold,124900.0,6.0,2.0,0.23,1774478.0,North Adams,Massachusetts,1247.0,1809.0,2022-03-21
99998,78465.0,sold,590000.0,4.0,4.0,0.20,1035102.0,Flower Mound,Texas,75022.0,3418.0,2021-11-30
99999,52776.0,for_sale,1050000.0,3.0,3.0,0.13,1820578.0,Denver,Colorado,80206.0,2276.0,2019-06-03

In [6]:
USA_ESTATE.isnull().any()

brokered_by        True
status            False
price              True
bed                True
bath               True
acre_lot           True
street             True
city               True
state             False
zip_code           True
house_size         True
prev_sold_date     True
dtype: bool

In [7]:
USA_ESTATE.isnull()

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,prev_sold_date
0,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,False,False
2,False,False,False,True,True,False,False,False,False,False,True,True
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,True,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,False,False,False,True,True,False,False,False,False,False,True,True
99996,False,False,False,False,False,False,False,False,False,False,False,False
99997,False,False,False,False,False,False,False,False,False,False,False,False
99998,False,False,False,False,False,False,False,False,False,False,False,False
99999,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
USA_ESTATE.isna().sum().sort_values(ascending =True)

status                0
state                 0
zip_code              7
city                 63
price                73
brokered_by         217
street              456
acre_lot          14862
bed               21550
bath              22947
house_size        25543
prev_sold_date    33012
dtype: int64

In [9]:
#so the most of the states which doesnot have preivous sold date they  would have

In [10]:
#commmon na value - fancy indexing 
common_na = USA_ESTATE[USA_ESTATE[['bed','bath','house_size','prev_sold_date']].isna().all(axis=1)]

In [11]:
common_na

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,prev_sold_date
2,53271.0,for_sale,75000.0,NaN,NaN,2.25,1877529.0,Oceola Township,Michigan,48855.0,NaN,NaN
4,79221.0,for_sale,169900.0,NaN,NaN,3.70,1998116.0,Holmen,Wisconsin,54636.0,NaN,NaN
7,22093.0,for_sale,59900.0,NaN,NaN,0.92,1884116.0,Wisconsin Dells,Wisconsin,53965.0,NaN,NaN
9,12163.0,for_sale,34900.0,NaN,NaN,1.17,1312439.0,Zirconia,North Carolina,28790.0,NaN,NaN
19,98775.0,for_sale,18000.0,NaN,NaN,0.15,1713771.0,Vass,North Carolina,28394.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
99977,49993.0,for_sale,110000.0,NaN,NaN,9.00,1852035.0,Scales Mound,Illinois,61075.0,NaN,NaN
99984,66484.0,for_sale,39950.0,NaN,NaN,4.70,1904562.0,Delta Junction,Alaska,99737.0,NaN,NaN
99988,14047.0,for_sale,70500.0,NaN,NaN,15.00,1884870.0,Hartsville,South Carolina,29550.0,NaN,NaN
99989,100432.0,for_sale,22500.0,NaN,NaN,0.50,1839276.0,Rio Rancho,New Mexico,87144.0,NaN,NaN
99995,78553.0,for_sale,249900.0,NaN,NaN,13.51,1876588.0,Sylva,North Carolina,28779.0,NaN,NaN

In [12]:
#removing this common nan data from tthe original data

In [13]:
USA_ESTATE = USA_ESTATE.drop(index = common_na.index)

In [14]:
USA_ESTATE

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,prev_sold_date
0,54239.0,sold,275000.0,1.0,1.0,NaN,1617038.0,Miami,Florida,33156.0,846.0,2022-02-28
1,90564.0,sold,399900.0,1.0,1.0,NaN,1497499.0,San Diego,California,92108.0,667.0,2022-04-28
3,12926.0,sold,325000.0,3.0,2.0,0.09,892999.0,Worcester,Massachusetts,1603.0,1409.0,2021-11-29
5,92677.0,sold,265000.0,2.0,1.0,0.12,819429.0,Merced,California,95340.0,901.0,2021-11-10
6,79183.0,for_sale,110000.0,NaN,NaN,0.21,212385.0,Bossier City,Louisiana,71111.0,NaN,2018-06-29
...,...,...,...,...,...,...,...,...,...,...,...,...
99994,6904.0,for_sale,850000.0,5.0,5.0,0.58,130783.0,Suwanee,Georgia,30024.0,5223.0,2022-04-14
99996,23001.0,sold,58000.0,2.0,1.0,0.16,663594.0,Streator,Illinois,61364.0,1050.0,2021-11-24
99997,81218.0,sold,124900.0,6.0,2.0,0.23,1774478.0,North Adams,Massachusetts,1247.0,1809.0,2022-03-21
99998,78465.0,sold,590000.0,4.0,4.0,0.20,1035102.0,Flower Mound,Texas,75022.0,3418.0,2021-11-30
99999,52776.0,for_sale,1050000.0,3.0,3.0,0.13,1820578.0,Denver,Colorado,80206.0,2276.0,2019-06-03

In [15]:
USA_ESTATE.isnull().any()

brokered_by        True
status            False
price              True
bed                True
bath               True
acre_lot           True
street             True
city               True
state             False
zip_code           True
house_size         True
prev_sold_date     True
dtype: bool

In [16]:
USA_ESTATE.isna().sum().sort_values(ascending= False)

prev_sold_date    18803
acre_lot          14511
house_size        11334
bath               8738
bed                7341
street              332
brokered_by         196
price                62
city                 23
zip_code              5
status                0
state                 0
dtype: int64

In [17]:
#so now we have the problem where preivous old date like 18k is not know means were not registered

In [18]:
[USA_ESTATE['price'].dropna()]

[0         275000.0
 1         399900.0
 3         325000.0
 5         265000.0
 6         110000.0
            ...
 99994     850000.0
 99996      58000.0
 99997     124900.0
 99998     590000.0
 99999    1050000.0
 Name: price, Length: 85729, dtype: float64]

In [19]:
USA_ESTATE = USA_ESTATE.dropna(subset=["price"])

In [20]:
USA_ESTATE

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,prev_sold_date
0,54239.0,sold,275000.0,1.0,1.0,NaN,1617038.0,Miami,Florida,33156.0,846.0,2022-02-28
1,90564.0,sold,399900.0,1.0,1.0,NaN,1497499.0,San Diego,California,92108.0,667.0,2022-04-28
3,12926.0,sold,325000.0,3.0,2.0,0.09,892999.0,Worcester,Massachusetts,1603.0,1409.0,2021-11-29
5,92677.0,sold,265000.0,2.0,1.0,0.12,819429.0,Merced,California,95340.0,901.0,2021-11-10
6,79183.0,for_sale,110000.0,NaN,NaN,0.21,212385.0,Bossier City,Louisiana,71111.0,NaN,2018-06-29
...,...,...,...,...,...,...,...,...,...,...,...,...
99994,6904.0,for_sale,850000.0,5.0,5.0,0.58,130783.0,Suwanee,Georgia,30024.0,5223.0,2022-04-14
99996,23001.0,sold,58000.0,2.0,1.0,0.16,663594.0,Streator,Illinois,61364.0,1050.0,2021-11-24
99997,81218.0,sold,124900.0,6.0,2.0,0.23,1774478.0,North Adams,Massachusetts,1247.0,1809.0,2022-03-21
99998,78465.0,sold,590000.0,4.0,4.0,0.20,1035102.0,Flower Mound,Texas,75022.0,3418.0,2021-11-30
99999,52776.0,for_sale,1050000.0,3.0,3.0,0.13,1820578.0,Denver,Colorado,80206.0,2276.0,2019-06-03

In [21]:
USA_ESTATE.isnull().any()

brokered_by        True
status            False
price             False
bed                True
bath               True
acre_lot           True
street             True
city               True
state             False
zip_code           True
house_size         True
prev_sold_date     True
dtype: bool

In [22]:
#since prev_sold_date of many  is not available we can simply say that it can represent as no record available 
USA_ESTATE['prev_sold_date'].fillna('No Record')

0        2022-02-28
1        2022-04-28
3        2021-11-29
5        2021-11-10
6        2018-06-29
            ...
99994    2022-04-14
99996    2021-11-24
99997    2022-03-21
99998    2021-11-30
99999    2019-06-03
Name: prev_sold_date, Length: 85729, dtype: object

In [23]:
USA_ESTATE.isnull().sum().sort_values(ascending=True)

status                0
price                 0
state                 0
zip_code              5
city                 23
brokered_by         196
street              332
bed                7333
bath               8715
house_size        11319
acre_lot          14492
prev_sold_date    18766
dtype: int64

In [24]:
USA_ESTATE.dropna(subset =["zip_code","city"],inplace=True)

C:\Users\Monu Verma\AppData\Local\Temp\ipykernel_20052\2149237190.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  USA_ESTATE.dropna(subset =["zip_code","city"],inplace=True)