# Insights of the Cleaned Estate dataset

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import sympy as sp

In [2]:
Estate_Data = pd.read_csv('cleaned_Estate.csv')

In [11]:
# Keep only rows where the price is greater than a reasonable minimum
Estate_Data = Estate_Data[Estate_Data['price'] > 1000]

In [20]:
"We basically did this because when we finded the answer of the problem with Top 10 cheapest cities with cheapest median houses we found out that there were houses with 0 dollar vlaue so we did before finding the answer of the quetion"

'We basically did this because when we finded the answer of the problem with Top 10 cheapest cities with cheapest median houses we found out that there were houses with 0 dollar vlaue so we did before finding the answer of the quetion'

In [12]:
Estate_Data

,Unnamed: 0,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,has_been_sold
0,0,54239.0,sold,275000.0,1.0,1.0,0.70,1617038.0,Miami,Florida,33156.0,846.0,1
1,1,90564.0,sold,399900.0,1.0,1.0,6.20,1497499.0,San Diego,California,92108.0,667.0,1
2,2,53271.0,for_sale,75000.0,2.5,2.0,2.25,1877529.0,Oceola Township,Michigan,48855.0,1697.5,0
3,3,12926.0,sold,325000.0,3.0,2.0,0.09,892999.0,Worcester,Massachusetts,1603.0,1409.0,1
4,4,79221.0,for_sale,169900.0,3.5,3.0,3.70,1998116.0,Holmen,Wisconsin,54636.0,2875.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
92813,99995,78553.0,for_sale,249900.0,2.0,2.0,13.51,1876588.0,Sylva,North Carolina,28779.0,929.0,0
92814,99996,23001.0,sold,58000.0,2.0,1.0,0.16,663594.0,Streator,Illinois,61364.0,1050.0,1
92815,99997,81218.0,sold,124900.0,6.0,2.0,0.23,1774478.0,North Adams,Massachusetts,1247.0,1809.0,1
92816,99998,78465.0,sold,590000.0,4.0,4.0,0.20,1035102.0,Flower Mound,Texas,75022.0,3418.0,1
92817,99999,52776.0,for_sale,1050000.0,3.0,3.0,0.13,1820578.0,Denver,Colorado,80206.0,2276.0,1

In [13]:
Estate_Data.head()

,Unnamed: 0,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,has_been_sold
0,0,54239.0,sold,275000.0,1.0,1.0,0.70,1617038.0,Miami,Florida,33156.0,846.0,1
1,1,90564.0,sold,399900.0,1.0,1.0,6.20,1497499.0,San Diego,California,92108.0,667.0,1
2,2,53271.0,for_sale,75000.0,2.5,2.0,2.25,1877529.0,Oceola Township,Michigan,48855.0,1697.5,0
3,3,12926.0,sold,325000.0,3.0,2.0,0.09,892999.0,Worcester,Massachusetts,1603.0,1409.0,1
4,4,79221.0,for_sale,169900.0,3.5,3.0,3.70,1998116.0,Holmen,Wisconsin,54636.0,2875.0,0

In [14]:
#The most expensive area to buy the houses 
top_10_cities = Estate_Data.groupby('city')['price'].median().sort_values(ascending = False).head(10)

In [15]:
print(f'THE TOP 10 cities with most expensive houses\n{top_10_cities}')

THE TOP 10 cities with most expensive houses
city
Aspen            49500000.0
Gulf Stream      30000000.0
Pebble Beach     29750000.0
Micanopy         14137500.0
Congress         12868550.0
Whitesville      12799950.0
Bridgehampton    12495000.0
Telluride        11299500.0
Amagansett       11247500.0
Locust Valley    10957500.0
Name: price, dtype: float64

In [16]:
"we are using the  median here because we want to find the median value so that if we use the mean  then some property like 100m$ can't inflate the data "

"we are using the  median here because we want to find the median value so that if we use the mean  then some property like 100m$ can't inflate the data "

In [17]:
#the top 10 cities with lowest median houses prices 
Low_10_cities = Estate_Data.groupby('city')['price'].median().sort_values(ascending = True).head(10)

In [21]:
print(f"The Top 10 cities with cheapest median houses\n{Low_10_cities})

SyntaxError: unterminated f-string literal (detected at line 1) (225461738.py, line 1)