### Finding meaning insights from the data and making a summary and making program to solve the problem

In [1]:
#importing things 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as pyplot 
import sympy as sp # for performing probability and the Other stuff

In [3]:
Estate_data = pd.read_csv('sample.csv')

In [9]:
Estate_data

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,prev_sold_date
0,54239.0,sold,275000.0,1.0,1.0,NaN,1617038.0,Miami,Florida,33156.0,846.0,2022-02-28
1,90564.0,sold,399900.0,1.0,1.0,NaN,1497499.0,San Diego,California,92108.0,667.0,2022-04-28
2,53271.0,for_sale,75000.0,NaN,NaN,2.25,1877529.0,Oceola Township,Michigan,48855.0,NaN,NaN
3,12926.0,sold,325000.0,3.0,2.0,0.09,892999.0,Worcester,Massachusetts,1603.0,1409.0,2021-11-29
4,79221.0,for_sale,169900.0,NaN,NaN,3.70,1998116.0,Holmen,Wisconsin,54636.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,78553.0,for_sale,249900.0,NaN,NaN,13.51,1876588.0,Sylva,North Carolina,28779.0,NaN,NaN
99996,23001.0,sold,58000.0,2.0,1.0,0.16,663594.0,Streator,Illinois,61364.0,1050.0,2021-11-24
99997,81218.0,sold,124900.0,6.0,2.0,0.23,1774478.0,North Adams,Massachusetts,1247.0,1809.0,2022-03-21
99998,78465.0,sold,590000.0,4.0,4.0,0.20,1035102.0,Flower Mound,Texas,75022.0,3418.0,2021-11-30
99999,52776.0,for_sale,1050000.0,3.0,3.0,0.13,1820578.0,Denver,Colorado,80206.0,2276.0,2019-06-03

In [10]:
Estate_data.describe()

,brokered_by,price,bed,bath,acre_lot,street,zip_code,house_size
count,99783.000000,9.992700e+04,78450.000000,77053.000000,85138.000000,9.954400e+04,99993.000000,74457.000000
mean,52910.010052,5.226363e+05,3.270491,2.494439,17.774187,1.008224e+06,52116.473973,2051.379373
std,30625.702830,1.328249e+06,1.428269,1.440801,875.871621,5.837411e+05,28969.291658,3184.107126
min,0.000000,0.000000e+00,1.000000,1.000000,0.000000,4.300000e+01,602.000000,100.000000
25%,23898.500000,1.650000e+05,3.000000,2.000000,0.160000,5.033332e+05,29588.000000,1300.000000
50%,52856.000000,3.250000e+05,3.000000,2.000000,0.260000,1.004810e+06,48211.000000,1758.000000
75%,79166.000000,5.500000e+05,4.000000,3.000000,0.990000,1.517856e+06,78070.000000,2410.000000
max,110138.000000,2.125000e+08,99.000000,198.000000,100000.000000,2.001347e+06,99999.000000,684327.000000

In [12]:
Estate_data.isnull().sum()#for adding the number of na values in them

brokered_by         217
status                0
price                73
bed               21550
bath              22947
acre_lot          14862
street              456
city                 63
state                 0
zip_code              7
house_size        25543
prev_sold_date    33012
dtype: int64

In [13]:
#filling the missing value

In [24]:
#filling the not registered value of the bed and bath accordingn to the meadian of the region using groupby 
Estate_data['bed'] = Estate_data.groupby('zip_code')['bed'].transform(lambda x : x.fillna(x.median()) )

In [25]:
Estate_data['bath'] = Estate_data.groupby('zip_code')['bath'].transform(lambda x : x.fillna(x.median()))

In [28]:
#filling the acre_lot with the same logic 
Estate_data['acre_lot'] = Estate_data.groupby('zip_code')['acre_lot'].transform(lambda x : x.fillna(x.median()))

In [30]:
Estate_data.isnull().sum()

brokered_by         217
status                0
price                73
bed                3714
bath               3884
acre_lot           1211
street              456
city                 63
state                 0
zip_code              7
house_size        25543
prev_sold_date    33012
dtype: int64

In [32]:
#filling the missing values with the meadian of that particular zip cod e
Estate_data['house_size'] = Estate_data.groupby('zip_code')['house_size'].transform(lambda x: x.fillna(x.median()))

In [37]:
"So here i am creating a has been sold column it is very common that house are either new so we are saying that if sold 1 if not sold 0 in order to predict that house has more value since it is new "

'So here i am creating a has been sold column it is very common that house are either new so we are saying that if sold 1 if not sold 0 in order to predict that house has more value since it is new '

In [36]:
Estate_data['has_been_sold'] = Estate_data['prev_sold_date'].notna().astype(int)

In [35]:
Estate_data

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,prev_sold_date,has_been_sold
0,54239.0,sold,275000.0,1.0,1.0,0.70,1617038.0,Miami,Florida,33156.0,846.0,2022-02-28,1
1,90564.0,sold,399900.0,1.0,1.0,6.20,1497499.0,San Diego,California,92108.0,667.0,2022-04-28,1
2,53271.0,for_sale,75000.0,2.5,2.0,2.25,1877529.0,Oceola Township,Michigan,48855.0,1697.5,NaN,0
3,12926.0,sold,325000.0,3.0,2.0,0.09,892999.0,Worcester,Massachusetts,1603.0,1409.0,2021-11-29,1
4,79221.0,for_sale,169900.0,3.5,3.0,3.70,1998116.0,Holmen,Wisconsin,54636.0,2875.0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,78553.0,for_sale,249900.0,2.0,2.0,13.51,1876588.0,Sylva,North Carolina,28779.0,929.0,NaN,0
99996,23001.0,sold,58000.0,2.0,1.0,0.16,663594.0,Streator,Illinois,61364.0,1050.0,2021-11-24,1
99997,81218.0,sold,124900.0,6.0,2.0,0.23,1774478.0,North Adams,Massachusetts,1247.0,1809.0,2022-03-21,1
99998,78465.0,sold,590000.0,4.0,4.0,0.20,1035102.0,Flower Mound,Texas,75022.0,3418.0,2021-11-30,1
99999,52776.0,for_sale,1050000.0,3.0,3.0,0.13,1820578.0,Denver,Colorado,80206.0,2276.0,2019-06-03,1

In [38]:
#now that we have solved the prev_sold date problem now we can move to removing the column
Estate_data = Estate_data.drop(columns = ['prev_sold_date'])

In [39]:
Estate_data

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,has_been_sold
0,54239.0,sold,275000.0,1.0,1.0,0.70,1617038.0,Miami,Florida,33156.0,846.0,1
1,90564.0,sold,399900.0,1.0,1.0,6.20,1497499.0,San Diego,California,92108.0,667.0,1
2,53271.0,for_sale,75000.0,2.5,2.0,2.25,1877529.0,Oceola Township,Michigan,48855.0,1697.5,0
3,12926.0,sold,325000.0,3.0,2.0,0.09,892999.0,Worcester,Massachusetts,1603.0,1409.0,1
4,79221.0,for_sale,169900.0,3.5,3.0,3.70,1998116.0,Holmen,Wisconsin,54636.0,2875.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,78553.0,for_sale,249900.0,2.0,2.0,13.51,1876588.0,Sylva,North Carolina,28779.0,929.0,0
99996,23001.0,sold,58000.0,2.0,1.0,0.16,663594.0,Streator,Illinois,61364.0,1050.0,1
99997,81218.0,sold,124900.0,6.0,2.0,0.23,1774478.0,North Adams,Massachusetts,1247.0,1809.0,1
99998,78465.0,sold,590000.0,4.0,4.0,0.20,1035102.0,Flower Mound,Texas,75022.0,3418.0,1
99999,52776.0,for_sale,1050000.0,3.0,3.0,0.13,1820578.0,Denver,Colorado,80206.0,2276.0,1

In [40]:
Estate_data.isnull().sum()

brokered_by       217
status              0
price              73
bed              3714
bath             3884
acre_lot         1211
street            456
city               63
state               0
zip_code            7
house_size       5229
has_been_sold       0
dtype: int64