### Finding meaning insights from the data and making a summary and making program to solve the problem

In [1]:
#importing things 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as pyplot 
import sympy as sp # for performing probability and the Other stuff

In [3]:
Estate_data = pd.read_csv('sample.csv')

In [50]:
Estate_data

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,has_been_sold
0,54239.0,sold,275000.0,1.0,1.0,0.70,1617038.0,Miami,Florida,33156.0,846.0,1
1,90564.0,sold,399900.0,1.0,1.0,6.20,1497499.0,San Diego,California,92108.0,667.0,1
2,53271.0,for_sale,75000.0,2.5,2.0,2.25,1877529.0,Oceola Township,Michigan,48855.0,1697.5,0
3,12926.0,sold,325000.0,3.0,2.0,0.09,892999.0,Worcester,Massachusetts,1603.0,1409.0,1
4,79221.0,for_sale,169900.0,3.5,3.0,3.70,1998116.0,Holmen,Wisconsin,54636.0,2875.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,78553.0,for_sale,249900.0,2.0,2.0,13.51,1876588.0,Sylva,North Carolina,28779.0,929.0,0
99996,23001.0,sold,58000.0,2.0,1.0,0.16,663594.0,Streator,Illinois,61364.0,1050.0,1
99997,81218.0,sold,124900.0,6.0,2.0,0.23,1774478.0,North Adams,Massachusetts,1247.0,1809.0,1
99998,78465.0,sold,590000.0,4.0,4.0,0.20,1035102.0,Flower Mound,Texas,75022.0,3418.0,1
99999,52776.0,for_sale,1050000.0,3.0,3.0,0.13,1820578.0,Denver,Colorado,80206.0,2276.0,1

In [51]:
Estate_data.describe()

,brokered_by,price,bed,bath,acre_lot,street,zip_code,house_size,has_been_sold
count,92818.000000,9.281800e+04,92818.000000,92818.000000,92818.000000,9.281800e+04,92818.000000,92818.000000,92818.000000
mean,52932.643571,5.281816e+05,3.258447,2.471476,14.563262,9.926239e+05,52716.678694,2033.172025,0.691094
std,30565.506260,1.140285e+06,1.323937,1.343499,836.638468,5.750514e+05,29057.820160,2876.661505,0.462045
min,0.000000,0.000000e+00,1.000000,1.000000,0.000000,9.800000e+01,602.000000,100.000000,0.000000
25%,24024.000000,1.750000e+05,3.000000,2.000000,0.150000,4.955315e+05,30004.000000,1345.000000,0.000000
50%,52895.000000,3.349000e+05,3.000000,2.000000,0.240000,9.866255e+05,49015.000000,1771.000000,1.000000
75%,79145.750000,5.579000e+05,4.000000,3.000000,0.680000,1.490479e+06,78390.000000,2357.000000,1.000000
max,110138.000000,8.000000e+07,99.000000,198.000000,100000.000000,2.001347e+06,99927.000000,684327.000000,1.000000

In [52]:
Estate_data.isnull().sum()#for adding the number of na values in them

brokered_by      0
status           0
price            0
bed              0
bath             0
acre_lot         0
street           0
city             0
state            0
zip_code         0
house_size       0
has_been_sold    0
dtype: int64

In [53]:
#filling the missing value

In [54]:
#filling the not registered value of the bed and bath accordingn to the meadian of the region using groupby 
Estate_data['bed'] = Estate_data.groupby('zip_code')['bed'].transform(lambda x : x.fillna(x.median()) )

In [55]:
Estate_data['bath'] = Estate_data.groupby('zip_code')['bath'].transform(lambda x : x.fillna(x.median()))

In [56]:
#filling the acre_lot with the same logic 
Estate_data['acre_lot'] = Estate_data.groupby('zip_code')['acre_lot'].transform(lambda x : x.fillna(x.median()))

In [57]:
Estate_data.isnull().sum()

brokered_by      0
status           0
price            0
bed              0
bath             0
acre_lot         0
street           0
city             0
state            0
zip_code         0
house_size       0
has_been_sold    0
dtype: int64

In [58]:
#filling the missing values with the meadian of that particular zip cod e
Estate_data['house_size'] = Estate_data.groupby('zip_code')['house_size'].transform(lambda x: x.fillna(x.median()))

In [59]:
"So here i am creating a has been sold column it is very common that house are either new so we are saying that if sold 1 if not sold 0 in order to predict that house has more value since it is new "

'So here i am creating a has been sold column it is very common that house are either new so we are saying that if sold 1 if not sold 0 in order to predict that house has more value since it is new '

In [60]:
Estate_data['has_been_sold'] = Estate_data['prev_sold_date'].notna().astype(int)

KeyError: 'prev_sold_date'

In [61]:
Estate_data

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,has_been_sold
0,54239.0,sold,275000.0,1.0,1.0,0.70,1617038.0,Miami,Florida,33156.0,846.0,1
1,90564.0,sold,399900.0,1.0,1.0,6.20,1497499.0,San Diego,California,92108.0,667.0,1
2,53271.0,for_sale,75000.0,2.5,2.0,2.25,1877529.0,Oceola Township,Michigan,48855.0,1697.5,0
3,12926.0,sold,325000.0,3.0,2.0,0.09,892999.0,Worcester,Massachusetts,1603.0,1409.0,1
4,79221.0,for_sale,169900.0,3.5,3.0,3.70,1998116.0,Holmen,Wisconsin,54636.0,2875.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,78553.0,for_sale,249900.0,2.0,2.0,13.51,1876588.0,Sylva,North Carolina,28779.0,929.0,0
99996,23001.0,sold,58000.0,2.0,1.0,0.16,663594.0,Streator,Illinois,61364.0,1050.0,1
99997,81218.0,sold,124900.0,6.0,2.0,0.23,1774478.0,North Adams,Massachusetts,1247.0,1809.0,1
99998,78465.0,sold,590000.0,4.0,4.0,0.20,1035102.0,Flower Mound,Texas,75022.0,3418.0,1
99999,52776.0,for_sale,1050000.0,3.0,3.0,0.13,1820578.0,Denver,Colorado,80206.0,2276.0,1

In [62]:
#now that we have solved the prev_sold date problem now we can move to removing the column
#Estate_data = Estate_data.drop(columns = ['prev_sold_date'])#droppingn the entire row

In [63]:
Estate_data

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,has_been_sold
0,54239.0,sold,275000.0,1.0,1.0,0.70,1617038.0,Miami,Florida,33156.0,846.0,1
1,90564.0,sold,399900.0,1.0,1.0,6.20,1497499.0,San Diego,California,92108.0,667.0,1
2,53271.0,for_sale,75000.0,2.5,2.0,2.25,1877529.0,Oceola Township,Michigan,48855.0,1697.5,0
3,12926.0,sold,325000.0,3.0,2.0,0.09,892999.0,Worcester,Massachusetts,1603.0,1409.0,1
4,79221.0,for_sale,169900.0,3.5,3.0,3.70,1998116.0,Holmen,Wisconsin,54636.0,2875.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,78553.0,for_sale,249900.0,2.0,2.0,13.51,1876588.0,Sylva,North Carolina,28779.0,929.0,0
99996,23001.0,sold,58000.0,2.0,1.0,0.16,663594.0,Streator,Illinois,61364.0,1050.0,1
99997,81218.0,sold,124900.0,6.0,2.0,0.23,1774478.0,North Adams,Massachusetts,1247.0,1809.0,1
99998,78465.0,sold,590000.0,4.0,4.0,0.20,1035102.0,Flower Mound,Texas,75022.0,3418.0,1
99999,52776.0,for_sale,1050000.0,3.0,3.0,0.13,1820578.0,Denver,Colorado,80206.0,2276.0,1

In [64]:
Estate_data.isnull().sum()

brokered_by      0
status           0
price            0
bed              0
bath             0
acre_lot         0
street           0
city             0
state            0
zip_code         0
house_size       0
has_been_sold    0
dtype: int64

In [65]:
#removing the price rows with na value 
Estate_data = Estate_data.dropna(subset = ['price'])